name: atom
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.8.1
  flutter_bloc: ^8.1.2
  rxdart: ^0.27.7
  flutter_gen: ^5.3.0
  flutter_svg: ^2.0.5
  equatable: ^2.0.5
  bloc: ^8.1.1
  loader_overlay: ^2.2.0
  supabase: ^1.7.0
  dropdown_button2: ^2.1.0
  bloc_concurrency: ^0.2.1
  mqtt_client: ^9.8.1
  uuid: ^3.0.7
  typed_data: ^1.3.2
  rfc_6901: ^0.1.1
  fl_chart: ^0.62.0
  intl: ^0.18.1
  badges: ^3.1.1
  onesignal_flutter: ^3.5.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.0
  
flutter_gen:
  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/colors/colors.xml

flutter_launcher_icons:
  image_path_android: "assets/icons/logo.png"
  image_path_ios: "assets/icons/logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/icons/logo.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icons/logo.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900

  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
